In [50]:
import pandas as pd

s1, s2 = pd.Series([1, 2, 3]), pd.Series([4, 5, 6])
print(s1)
print(s2)
print("Addition\n",s1 + s2)
print("Substraction\n",s1 - s2)
print("Multiplication\n",s1 * s2)
print("Division\n",s1 / s2)-

0    1
1    2
2    3
dtype: int64
0    4
1    5
2    6
dtype: int64
Addition
 0    5
1    7
2    9
dtype: int64
Substraction
 0   -3
1   -3
2   -3
dtype: int64
Multiplication
 0     4
1    10
2    18
dtype: int64
Division
 0    0.25
1    0.40
2    0.50
dtype: float64


In [63]:
def non_duplicate_words(file_name):
    with open(file_name, 'r') as file:
        words = file.read().lower().split()
        unique_words = set(words)
        return sorted(unique_words)

file_name = input("Enter the name of the text file: ")
words = non_duplicate_words(file_name)

if words:
    print("\nNon-duplicate words in ascending order:")
    print("\n".join(words))


Enter the name of the text file: data/input.txt

Non-duplicate words in ascending order:
are
everyone
fine
hello
hii
how
world
you


In [58]:
def count_vowels_consonants(file_path):
    vowels = set('aeiouAEIOU')
    with open(file_path, 'r') as file:
        text = file.read()
        vowels_count = sum(1 for c in text if c in vowels)
        consonants_count = sum(1 for c in text if c.isalpha() and c not in vowels)
    print(f"Vowels: {vowels_count}, Consonants: {consonants_count}")

count_vowels_consonants(input("Enter the file path: "))

Enter the file path: data/input.txt
Vowels: 24, Consonants: 24


In [57]:
def remove_newlines(input_file, output_file):
    with open(input_file, 'r') as infile, open(output_file, 'w') as outfile:
        outfile.write(infile.read().replace('\n', ' '))

remove_newlines(input("Enter the input file path: "), input("Enter the output file path: "))

Enter the input file path: data/input.txt
Enter the output file path: data/output.txt


In [56]:
import csv

def copy_csv(input_file, output_file):
    with open(input_file, 'r') as infile, open(output_file, 'w', newline='') as outfile:
        csv.writer(outfile).writerows(csv.reader(infile))

copy_csv(input("Enter the input CSV file path: "), input("Enter the output CSV file path: "))

Enter the input CSV file path: data/day.csv
Enter the output CSV file path: data/copy_data.csv


In [ ]:
import numpy as np

matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

print("Addition:\n", matrix1 + matrix2)
print("\nSubtraction:\n", matrix1 - matrix2)
print("\nMultiplication:\n", matrix1 * matrix2)
print("\nDivision:\n", matrix1 / matrix2)

In [ ]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
print(A)
print("Determinant of matrix : ",np.linalg.det(A))

In [ ]:
import numpy as np

A = np.array([[1, 2], [2, 1]])
print(A)
print('Is matrix symmetric : ',np.allclose(A, A.T))

In [45]:
import numpy as np

A = np.array([[0, 1], [-1, 0]])
print(A)
print("Is matrix skew symmetric : ",np.allclose(A, -A.T))

[[ 0  1]
 [-1  0]]
Is matrix skew symmetric :  True


In [29]:
import numpy as np

A = np.array([[0, 2-1j], [2+1j,0]])
print(A)
print(np.allclose(A, A.conj().T))

[[0.+0.j 2.-1.j]
 [2.+1.j 0.+0.j]]
True


In [43]:
import numpy as np

A = np.array([[0, -2-1j], [2+1j,0]])
print(A)
print("IS matrix skew hermitian? ",np.allclose(A, -A.conj().T))


[[ 0.+0.j -2.-1.j]
 [ 2.+1.j  0.+0.j]]
[[-0.+0.j -2.+1.j]
 [ 2.-1.j -0.+0.j]]
IS matrix skew hermitian?  False


In [20]:
import numpy as np

# Define a matrix
A = np.array([[1, 0], [0, -1]])
print(A)
print("Is matrix orthogonal? ",np.allclose(np.dot(A,A.T), np.eye(A.shape[0])))


[[ 1  0]
 [ 0 -1]]
Is matrix orthogonal?  True


In [17]:
import numpy as np

# Define a matrix
A = np.array([[1, 2, 3], [0, 9, 5], [0, 0, 6]])
print(A)
print("Array is upper triangular matrix : ",np.allclose(A, np.tril(A)))
print("Array is lower triangular matrix : ",np.allclose(A, np.triu(A)))


[[1 2 3]
 [0 9 5]
 [0 0 6]]
Array is upper triangular matrix :  False
Array is lower triangular matrix :  True


In [11]:
import numpy as np

A = np.array([[1, 2], [3, 4]])

adjoint = np.transpose(np.linalg.inv(A).T * np.linalg.det(A))
print(adjoint)


[[ 4. -2.]
 [-3.  1.]]
